version: "1.0"
# docker compose -f docker-compose-cuatesportainer.yml --env-file cuatesportainer-variables.env up -d
# docker compose -f docker-compose-cuatesportainer.yml --env-file cuatesportainer-variables.env down
## -f specify docker-compose file
## --env-file specify environment file
## -d detached mode
## -p project name
## Below are examples of using the -p flag to give it a project name if not given in the environment file
## i.e. docker compose -f docker-compose-cuatesportainer.yml --env-file cuatesportainer-variables.env -p cuates-portainer up -d
## i.e. docker compose -f docker-compose-cuatesportainer.yml --env-file cuatesportainer-variables.env -p cuates-portainer down
## Update all or one container(s) without downing all container(s)
# docker compose -f docker-compose-cuatesserver.yml --env-file cuatesserver-variables.env pull [container_name]
# docker compose -f docker-compose-cuatesserver.yml --env-file cuatesserver-variables.env up -d [container_name]
## Remove dangling and or unused images
## i.e. docker image prune
# docker stop portainer
# docker rm portainer
services:
  portainer:
    image: ${PRTR_OF_CONTAINER_IMAGE}
    container_name: portainer
    command: ${PRTR_SOCK_COMMAND}
    environment:
      # - PUID=${PUID_VALUE}
      # - PGID=${PGID_VALUE}
      - TZ=${TIMEZONE_LOCATION}
    volumes:
      - ${PRTR_SOCK_PATH}:/var/run/docker.sock
      - ${PRTR_DATA_PATH}:/data
    ports:
      - ${PRTR_EXTERNAL_PORT}:${PRTR_INTERNAL_PORT}
      - ${PRTR_EXTERNAL_TRAFFIC_PORT}:${PRTR_INTERNAL_TRAFFIC_PORT}
    restart: unless-stopped

networks:
  default:
    name: docker-npm-network
    external: true
