version: '2'
# docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env up -d
# docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env down
## -f specify docker-compose file
## --env-file specify environment file
## -d detached mode
## -p project name
## Below are examples of using the -p flag to give it a project name if not given in the environment file
## i.e. docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env -p nginx-webserver up -d
## i.e. docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env p nginx-webserver down
## Update all or one container(s) without downing all container(s)
## docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env pull [container_name]
## docker compose -f docker-compose-webserver.yml --env-file cuateswebserver-variables.env up -d [container_name]
## Remove dangling and or unused images
## i.e. docker image prune
# docker stop nginx-webserver
# docker rm nginx-webserver
# docker stop php-webserver
# docker rm php-webserver
services:
  nginx-webserver:
    build:
      context: ./nginx/
      args:
        TIMEZONE_LOCATION: ${TIMEZONE_LOCATION}
    container_name: nginx-webserver
    environment:
      # - PUID=${PUID_VALUE}
      # - PGID=${PGID_VALUE}
      - TZ=${TIMEZONE_LOCATION}
    ports:
      - ${NXWS_EXTERNAL_PORT}:${NXWS_INTERNAL_PORT}
    volumes:
      - ${NPWS_PATH}:/var/www/html/
    restart: unless-stopped

  php-webserver:
    build:
      context: ./php/
      args:
        TIMEZONE_LOCATION: ${TIMEZONE_LOCATION}
    container_name: php-webserver
    environment:
      # - PUID=${PUID_VALUE}
      # - PGID=${PGID_VALUE}
      - TZ=${TIMEZONE_LOCATION}
    expose:
      - ${PPWS_EXPOSE_PORT}
    volumes:
      - ${NPWS_PATH}:/var/www/html/
    restart: unless-stopped

networks:
  default:
    name: docker-npm-network
    external: true