version: "1.0"
# docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env up -d
# docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env down
## -f specify docker-compose file
## --env-file specify environment file
## -d detached mode; execution do not show in the terminal window
## -p project name
## Below are examples of using the -p flag to give it a project name if not given in the environment file
## i.e. docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env -p rssfeed up -d
## i.e. docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env -p rssfeed down
## Update all or one container(s) without downing all container(s)
# docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env pull [container_name]
# docker compose -f docker-compose-rssfeed.yml --env-file rssfeed-variables.env up -d [container_name]
## Remove dangling and or unused images
## i.e. docker image prune
# docker stop <container_name>
# docker rm <container_name>
services:
  rssfeed:
    build:
      context: rssfeeddatabase
      args:
        TIMEZONE_LOCATION: ${TIMEZONE_LOCATION}
    container_name: rssfeedpy
    environment:
      # - PUID=${PUID_VALUE}
      # - PGID=${PGID_VALUE}
      - TZ=${TIMEZONE_LOCATION}
    volumes:
      - ${RSFD_PATH}:/usr/local/src/rssfeeddatabase
    restart: unless-stopped

  rssfeedreddit:
    build:
      context: rssfeedredditdatabase
      args:
        TIMEZONE_LOCATION: ${TIMEZONE_LOCATION}
    container_name: rssfeedredditpy
    environment:
      # - PUID=${PUID_VALUE}
      # - PGID=${PGID_VALUE}
      - TZ=${TIMEZONE_LOCATION}
    volumes:
      - ${RFRD_PATH}:/usr/local/src/rssfeedredditdatabase
    restart: unless-stopped

networks:
  default:
    name: docker-npm-network
    external: true
